from __future__ import annotations

import re
from html import escape

from docbuildr.crawler import MarkdownPage
from docbuildr.metadata import BookMetadata
from docbuildr.models import Chapter


class BookBuilder:
    """Build a complete Markdown book."""

    def build(
        self,
        docs: list[MarkdownPage],
        metadata: BookMetadata,
    ) -> str:
        chapters = self.build_chapters(docs)

        parts = [
            self.build_cover(metadata),
            self.build_about(metadata),
            self.build_toc(chapters),
            self.build_chapters_markdown(chapters),
        ]

        return "\n\n".join(parts)

    @staticmethod
    def slugify(text: str) -> str:
        """Convert a heading into a stable HTML anchor."""

        text = text.lower()

        text = re.sub(
            r"[^a-z0-9]+",
            "-",
            text,
        )

        return text.strip("-")

    def build_cover(
        self,
        metadata: BookMetadata,
    ) -> str:
        return f"""
<div class="cover">

<h1>{metadata.title}</h1>

<div class="subtitle">
Professional Documentation
</div>

<div class="source">
{metadata.source}
</div>

<div class="date">
Generated on {metadata.generated}
</div>

</div>

<div class="page-break"></div>
""".strip()

    def build_about(
        self,
        metadata: BookMetadata,
    ) -> str:
        return f"""
# About this Book

| | |
|---|---|
| **Title** | {metadata.title} |
| **Source** | {metadata.source} |
| **Generated** | {metadata.generated} |
| **Built with** | DocBuildr |

---

## Copyright

This document was automatically generated by **DocBuildr**.

The documentation content belongs to its original authors.

This PDF is intended for offline reading only.

<div class="page-break"></div>
""".strip()

    def build_toc(
        self,
        chapters: list[Chapter],
    ) -> str:
        items = []

        for number, chapter in enumerate(
            chapters,
            start=1,
        ):
            anchor = self.slugify(
                chapter.title,
            )

            title = escape(
                chapter.title,
            )

            items.append(
                self.build_toc_item(
                    number,
                    anchor,
                    title,
                )
            )

        toc_items = "\n".join(items)

        return f"""
<nav class="toc" aria-labelledby="contents-title">
<h1 id="contents-title">Contents</h1>
<ol class="toc-list">
{toc_items}
</ol>
</nav>

<div class="page-break"></div>
""".strip()

    @staticmethod
    def build_toc_item(
        number: int,
        anchor: str,
        title: str,
    ) -> str:
        return f"""
<li class="toc-item">
<a class="toc-link" href="#{anchor}">
<span class="toc-number" aria-hidden="true">{number}</span>
<span class="toc-title">{title}</span>
<span class="toc-dots" aria-hidden="true"></span>
<span class="toc-page"></span>
</a>
</li>
""".strip()

    @staticmethod
    def build_chapters(
        docs: list[MarkdownPage],
    ) -> list[Chapter]:
        return [
            Chapter(
                title=doc.title,
                markdown=doc.markdown.strip(),
            )
            for doc in docs
        ]

    def build_chapters_markdown(
        self,
        chapters: list[Chapter],
    ) -> str:
        parts: list[str] = []

        for chapter in chapters:
            anchor = self.slugify(
                chapter.title,
            )

            parts.append(
                f"""
<a id="{anchor}"></a>

{chapter.markdown}
""".strip()
            )

        return "\n\n".join(parts)
