from __future__ import annotations

from docbuildr.crawler import MarkdownPage
from docbuildr.metadata import BookMetadata
from docbuildr.models import Chapter


class BookBuilder:
    """Build the merged markdown book."""

    def build(
        self,
        docs: list[MarkdownPage],
        metadata: BookMetadata,
    ) -> str:

        chapters = self.build_chapters(docs)

        sections: list[str] = []

        sections.append(
            self.build_cover(metadata)
        )

        sections.append(
            self.build_toc(chapters)
        )

        sections.append(
            self.render_chapters(chapters)
        )

        return "\n\n".join(sections)

    def build_cover(
        self,
        metadata: BookMetadata,
    ) -> str:

        return f"""
<div class="cover">

<h1>{metadata.title}</h1>

<div class="subtitle">
Generated by DocBuildr
</div>

<div class="source">
{metadata.source}
</div>

<div class="date">
{metadata.generated}
</div>

</div>

<div class="page-break"></div>
"""

    def build_toc(
        self,
        chapters: list[Chapter],
    ) -> str:

        lines = [
            "# Contents",
            "",
        ]

        for i, chapter in enumerate(
            chapters,
            start=1,
        ):
            lines.append(
                f"{i}. {chapter.title}"
            )

        return "\n".join(lines)

    def build_chapters(
        self,
        docs: list[MarkdownPage],
    ) -> list[Chapter]:

        return [

            Chapter(
                title=doc.title,
                markdown=doc.markdown.strip(),
            )

            for doc in docs

        ]

    def render_chapters(
        self,
        chapters: list[Chapter],
    ) -> str:

        return "\n\n".join(
            chapter.markdown
            for chapter in chapters
        )
