from __future__ import annotations

from pathlib import Path

from playwright.sync_api import sync_playwright


class PDFExporter:
    """Export HTML to PDF."""

    def export(
        self,
        html: Path,
        pdf: Path,
    ) -> None:

        html = html.resolve()
        pdf = pdf.resolve()

        with sync_playwright() as p:

            browser = p.chromium.launch(
                headless=True,
            )

            page = browser.new_page()

            page.goto(
                html.as_uri(),
                wait_until="networkidle",
            )

            page.emulate_media(
                media="print",
            )

            page.pdf(
                path=str(pdf),
                print_background=True,
                prefer_css_page_size=True,

                # Header / Footer
                display_header_footer=True,

                header_template="""
<div style="
width:100%;
font-size:8px;
text-align:center;
color:#888;
"></div>
""",

                footer_template="""
<div style="
width:100%;
font-size:8px;
padding:0 18mm;
display:flex;
justify-content:space-between;
align-items:center;
color:#666;
font-family:Arial,sans-serif;
">

<span>
Generated by <strong>DocBuildr</strong>
</span>

<span>
Page
<span class="pageNumber"></span>
of
<span class="totalPages"></span>
</span>

</div>
""",

                margin={
                    "top": "20mm",
                    "bottom": "20mm",
                    "left": "18mm",
                    "right": "18mm",
                },
            )

            browser.close()
